# 关键词 lore是怎么样的这里就怎么样，"[data]"+替换lore里的具体数值，
# 可以用.*替代任意数量的文字，可以用关键词
# 例如 原lore：普通攻击有10%的概率对目标造成最大血量20%的伤害
# 关键词：普通攻击.*有[data]%.*的概率.*最大血量[data]%.*的伤害
# 等效 关键词：普通攻击有[data]%的概率对目标造成最大血量[data]%的伤害
# 例如 lore是 "减伤: 20.0%"" 就填 "减伤：[data]%   如果懂正则表达式的话确保匹配的是百分比伤害就行
# 概率必须在前
# 百分比伤害插件设置
百分比伤害: # 根据对方血量
  开关: true      # true为开 false为关
  关键词: "普通攻击.*有[data]%.*的概率.*最大血量[data]%.*的伤害"
  命令提示: "&d你的下一次攻击将额外造成目标[data]%的伤害!"
  攻击提示: "&b你刚刚的攻击造成了目标[data]%生命上限的额外真实伤害!"
  # 玩家受到伤害的最大百分比 单位:%
  玩家最大百分比: 100.00
  # 怪物受到伤害的最大百分比 单位:%
  怪物最大百分比: 5.00

百分比减伤: # 护甲及手上物品
  开关: true
  关键词: "减伤: [data]%"

百分比增伤-普通伤害: # 根据自身血量
  开关: true
  # 普通伤害
  普攻概率: "攻击目标有[data]%的几率"
  普攻倍率: "施加自身最大血量的[data]%的攻击伤害"
  触发提示: "&b你的攻击造成了额外自身血量[data]%的普通伤害"
  命令提示: "&c你的下一次攻击将造成额外自身血量[data]%的普通伤害"

百分比增伤-真实伤害: # 根据自身血量
  # 真实伤害
  开关: true
  真攻概率: "攻击目标有[data]%的几率"
  真攻倍率: "施加自身最大血量的[data]%的真实伤害"
  触发提示: "&b你的攻击造成了额外自身血量[data]%的真实伤害"
  命令提示: "&c你的下一次攻击将造成自身血量[data]%的真实伤害"

必中: #次功能只针对闪避
 开关: true
 关键词: "攻击有[data]%的几率，令对方无法闪避"
 单次提示: "&b你的下次攻击将无法被闪避"
 时间提示: "&b你的攻击在[data]秒内将无法被闪避"
 成功提示: "&b你成功无视了[data]的闪避"