# 关键词 lore是怎么样的这里就怎么样，"[data]"+替换lore里的具体数值，
# 可以用.*替代任意数量的文字，可以用关键词
# 例如 原lore：普通攻击有10%的概率对目标造成最大血量20%的伤害
# 关键词：普通攻击.*有[data]%.*的概率.*最大血量[data]%.*的伤害
# 等效 关键词：普通攻击有[data]%的概率对目标造成最大血量[data]%的伤害
# 例如 lore是 "减伤: 20.0%"" 就填 "减伤：[data]%   如果懂正则表达式的话确保匹配的是百分比伤害就行
# 概率必须在前

# 百分比伤害 根据对方血量
PercentageDamage:
  # true为开 false为关
  Switch: true
  KeyWord: "普通攻击.*有[data]%.*的概率.*最大血量[data]%.*的伤害"
  Tip1: "&d你的下一次攻击将额外造成目标[data]%的伤害!"
  Tip2: "&d你的攻击将额外造成目标[data]%的伤害,持续[time]秒"
  Tip3: "&b你刚刚的攻击造成了目标[data]%生命上限的额外真实伤害!"
  # 玩家受到伤害的最大百分比 单位:%
  PlayerMaxPercentage: 100.00
  # 怪物受到伤害的最大百分比 单位:%
  MobMaxPercentage: 5.00

# 百分比减伤 护甲及手上物品
PercentageDecreaseInjury:
  Switch: true
  KeyWord: "减伤: [data]%"
  Tip: "&d你在[second]秒内增加减伤[data]%!"

# 百分比破伤 手上物品
ProtectionBreaker:
  Switch: true
  KeyWord: "普通攻击.*有[data]%.*的概率.*减少目标[data]%的减伤"
  Tip1: "&d你的下一次攻击将减少目标[data]%的减伤!"
  Tip2: "&d你的攻击将减少目标[data]%的减伤,持续[time]秒!"
  Tip3: "&b你刚刚的攻击减少了目标减伤的[data]%!"


# 百分比增伤-普通伤害 根据自身最大血量
PercentageNormalDamage:
  Switch: true
  # 普通伤害
  KeyWord1: "攻击目标有[data]%的几率"
  KeyWord2: "施加自身最大血量的[data]%的攻击伤害"
  Tip1: "&b你的攻击造成了额外自身血量[data]%的普通伤害"
  Tip2: "&c你的下一次攻击将造成额外自身血量[data]%的普通伤害"
  Tip3: "&c你的攻击将造成额外自身血量[data]%的普通伤害,持续[time]秒"

# 百分比增伤-真实伤害 根据自身最大血量
PercentageRealDamage:
  # 真实伤害
  Switch: true
  KeyWord1: "攻击目标有[data]%的几率"
  KeyWord2: "施加自身最大血量的[data]%的真实伤害"
  Tip1: "&b你的攻击造成了额外自身血量[data]%的真实伤害"
  Tip2: "&c你的下一次攻击将造成自身血量[data]%的真实伤害"
  Tip3: "&c你的攻击将造成额外自身血量[data]%的真实伤害,持续[time]秒"

# 必中 此功能只针对闪避
MustHit:
  Switch: true
  KeyWord: "攻击有[data]%的几率，令对方无法闪避"
  Tip1: "&b你的下次攻击将无法被闪避"
  Tip2: "&b你的攻击在[data]秒内将无法被闪避"
  Tip3: "&b你成功无视了[data]的闪避"

# 血量修改
HealthModify:
  Switch: true
  KeyWord1: "手持物品提升[data]额外生命上限"
  KeyWord2: "攻击有[data]%的几率降低目标[data]的血量上限,持续[time]秒"
  Tip1: "&b你的生命上限被减少了[data],持续[time]秒"
  Tip2: "&b你的生命上限增加了[data],持续[time]秒"
  Tip3: "&b你的攻击使目标生命上限被减少了[data],持续[time]秒"
  Tip4: "&b你的攻击将减少目标生命上限[data],持续[time]秒"



# 范围攻击
RangeAttack:
  Switch: true
  KeyWord: "范围震荡+[data]"

# 流血
Bleed:
  Switch: true
  KeyWord1: "流血几率+[data]%"
  KeyWord2: "每秒流血伤害:[data]"
  KeyWord3: "流血持续:[data]秒"
  KeyWord4: "每[data]秒流血一次"

# 破甲
SunderArmor:
  Switch: true
  KeyWord: "攻击有[data]%的几率无视目标护甲值"
  Tip1: "&b你的攻击在[time]秒内有[data]%的几率将无视目标护甲"
  Tip2: "&b你的攻击无视了目标的护甲"

# 回血
Heal:
  Switch: true
  KeyWord: "攻击有[data]%的几率恢复目标[data]血量"
  Tip1: "&b你的每次攻击将在[time]秒对目标治愈[data]血"
  Tip2: "&c[player]给你加了[data]血"
