name: CustomisedAttributes
main: top.iseason.customisedattributes.Main
version: 1.5.9
commands:
  CustomisedAttributes:
    aliases: [ ca ]
    description: 重置插件配置
  percentageA:
    description: 设置下一次攻击必定造成百分比伤害(以目标最大生命为准)，概率为x%
    aliases: [ strange ]
  percentageID:
    description: 设置下一次攻击必定造成百分比普通伤害(以自身血量)，概率为x%
    aliases: [ pid ]
  percentageIRD:
    description: 设置下一次攻击必定造成百分比真实伤害(以自身血量)，概率为x%
    aliases: [ pird ]
  mustHit:
    description: 设置攻击必中
    aliases: [ mh ]
  CustomisedAttributesBlackList:
    aliases: [ cabl ]
    description: 添加百分比黑名单
  protectionBreaker:
    aliases: [ pb ]
  percentageProtection:
    aliases: [ pp ]
    description: 一定时间内增加百分比减伤
  healthModifier:
    aliases: [ hm ]
    description: 修改血量
  ArmourPenetration:
    aliases: [ ap, ia ]
    description: 破甲
  healths:
    aliases: [ hl ]
    description: 给别人回血
